#%RAML 1.0
title: updateQueryDynamicDemo
description: need to update a row in a table for only those columns that come in the payload
/update:
  post:
    body:
      application/json:
        example:
          {
            "name": "update_name",
            "id": "update_id"
          }
    
    
    